name: digiselfie_sdk
description: >-
  SDK for DigiSelfie platform. Use this SDK to connect to DigiSelfie API and
  build interactive social networking applications on Flutter.
version: 0.0.3
author: Constantine Kurianoff <constantine@kurianoff.com>
homepage: https://www.digiselfie.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.0
  test: '>=0.12.42 <2.0.0'
  json_serializable: ^3.0.0
  build_runner: ^1.0.0
  build_test: ^0.10.3
  pedantic: ^1.8.0+1

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
